package com.yibao.biggirl.model.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.yibao.biggirl.model.favorite.FavoriteBean;

import com.yibao.biggirl.model.greendao.FavoriteBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig favoriteBeanDaoConfig;

    private final FavoriteBeanDao favoriteBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        favoriteBeanDaoConfig = daoConfigMap.get(FavoriteBeanDao.class).clone();
        favoriteBeanDaoConfig.initIdentityScope(type);

        favoriteBeanDao = new FavoriteBeanDao(favoriteBeanDaoConfig, this);

        registerDao(FavoriteBean.class, favoriteBeanDao);
    }
    
    public void clear() {
        favoriteBeanDaoConfig.clearIdentityScope();
    }

    public FavoriteBeanDao getFavoriteBeanDao() {
        return favoriteBeanDao;
    }

}
