package com.yibao.biggirl.model.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.yibao.biggirl.model.favoriteweb.FavoriteWebBean;
import com.yibao.biggirl.model.music.MusicInfo;

import com.yibao.biggirl.model.greendao.FavoriteWebBeanDao;
import com.yibao.biggirl.model.greendao.MusicInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig favoriteWebBeanDaoConfig;
    private final DaoConfig musicInfoDaoConfig;

    private final FavoriteWebBeanDao favoriteWebBeanDao;
    private final MusicInfoDao musicInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        favoriteWebBeanDaoConfig = daoConfigMap.get(FavoriteWebBeanDao.class).clone();
        favoriteWebBeanDaoConfig.initIdentityScope(type);

        musicInfoDaoConfig = daoConfigMap.get(MusicInfoDao.class).clone();
        musicInfoDaoConfig.initIdentityScope(type);

        favoriteWebBeanDao = new FavoriteWebBeanDao(favoriteWebBeanDaoConfig, this);
        musicInfoDao = new MusicInfoDao(musicInfoDaoConfig, this);

        registerDao(FavoriteWebBean.class, favoriteWebBeanDao);
        registerDao(MusicInfo.class, musicInfoDao);
    }
    
    public void clear() {
        favoriteWebBeanDaoConfig.clearIdentityScope();
        musicInfoDaoConfig.clearIdentityScope();
    }

    public FavoriteWebBeanDao getFavoriteWebBeanDao() {
        return favoriteWebBeanDao;
    }

    public MusicInfoDao getMusicInfoDao() {
        return musicInfoDao;
    }

}
